--- 
title: "Experimental Biology Stats Practicals"
author: "Francoise Cabada-Blanco"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo:  BlancoFC/EB_StatswithR
description: "This is a GitBook to accompany the Statistics L4 practical sessions within the Experimental Biology module"
# bookdown::render_book("index.Rmd")
---

# Learning to talk R

## What is R?

R is an open source programming language. This language, is optimized for statistical analysis and data visualization. It was developed in 1992, and has now a myriad of tools for analysing and reporting data. The main tools that allows you to make calculations, run and automate analyses in R, are called packages.

Packages are a bundle of functions. If you remember from class, we can see function as something that receives an input, changes that input in a specified manner and produces an output. In programming, a function does exactly the same always consistently. That is, we know that as long as we provide an input to which the function can make the changes it has been specified to do, these changes will always be consistent as long as we do not change the function. 

##### Scheme of packages and functions

All functions within R packages work in this way and are built for specific purposes, usually as part of a workflow. Most function within a package will be destined to do tasks needed to conduct a type or family of analyses or visualisation procedures to a set of data. For example, the package "lubridate" has a bundle of functions to work with dates and the package "readr" has a series of functions for R to be able to read different format of files.

We can download the packages we need (we will refresh how to do this later on) into our own library and load them only when we need them as when you take a book from the library to study Oceanography without having to also check-out and carry all other books for the academic year. All these packages and their documentation are within a repository online called the the Comprehensive R Archive Network or CRAN.

## Why use R?

R is very popular among scholars and researchers for three main reasons:
1. It is free and Open source. This is important not only because of financial reasons, but because tools are always improving and new ones are developed constantly. You do not have to wait for a full release of a new version as with most proprietary software.
2. It has a very big, and active, community of users and developers. This offers two important advantages:
2.1. There are vast resources online both free and paid to help you learn anything you want or to solve most of the issues you might encounter while you learn to talk R.
2.2. That big community has many super users that build custom packages to address very specific, niche analyses or user cases. In January 2022, the list of CRAN packages reaches >18,800. Chances are there is a package and/or set of packages that will allow you to do any analysis you want to do. Imagine how many software you would need -and pay for- to do that.
3. Finally, because it is the most used programming language for data analysis and visualisation in Biological Sciences and therefore, a key technological skill that will make you a competitive professional in the job market.

## How easy it is to learn to talk R?

As with any new language, practice is essential to become fluent in R. However, there are many tools at your disposal that enables you to harness the power of R, without getting to the level of a "native" speaker!

Programming languages are a kind of computer languages that comprises a set of instructions, following a specific syntax that allows computers to understand what it is we are instructing them to do. The computer does not speak R either, but there are interpreters that speak bot "computer" and programming languages. R is an interpreted language. That is why when you write an instruction we say it is a command.

You do not even have to deal with the interpreter. You can tell the computer what to do through an IDE (Integrated Development Environment).The IDE as the name describes it is a user interface that integrates functionalities needed for effective communication when speaking R. The IDE we will use is R Studio, arguably the best IDE for R. 


# R Studio

This is to date, the most user-friendly IDE for R and one that makes our life easy. R Studio significantly helps in lowering the learning curve for you to start talking R.

## Installation

I assume you all are familiarised with R and R Studio from the session given on GS1. If you need a refresher, now is a good time to watch the recorded session again.

To install R Studio, go to AppsAnywhere and write R Studio in the search box. Click install and wait until the Cloud Pager App has finished. Now launch it from the Apps menu.

You will see something like this:


#### Insert R Console with panels

The IDE has four main windows or panels. Within each there are several tabs. The position of those tabs can be customised in the settings, through Tools> Global Options and select Pane layout from the right vertical menu. 

The two main panels are the console and source.

- The Console: you can think of the console as the interpreter, who besides translating your commands written in R to the computer, also tells you, in written, how is the process going while your commands are being executed. In the console, you will know when the computer is "listening" and ready to receive a command when a '>' is visible. You can then write a command next to it. This is called a command line and it will be executed once you press enter

- The Source: This usually contains the suite of commands you instruct the computer to do, known as a script. The simplest format of a script is a text file. In R studio you can run a command directly from the source file without having to copy and paste on the command line. That is you can run part or the whole script from the file itself. From this point on, we will call _run_ the action of telling the interpreter what you want the computer to do.

Then we have several other tabs. I will go over the ones you will use the most:

- Help: here you can get information for every function in R. Just write the function name in the search box at the top left. The help page for each function provides first a description of what the function does, then a example of how to use it and then a list of the arguments it needs with details for each. Some of the arguments need to be provided by you and some are built in with settings that you may change. Lastly it provides an example of the different ways in which you can use the function.

- Plots: here is where you will be able to see the plots or graphs you make, with options to enlarge them, export them and save them in different formats

- Viewer: this tab is where you will be able to see any dataset you "read" (i.e., upload or import) or make during your session.

- Files: This works like a file explorer and allows you to see a list of the files on a directory

- Environment: here a list of all the things you make and assign a name to during your session. It also has a button to read or import files and to export those things you have made as files.

- Packages: this is a list of all the packages that are installed in your library, and the ones that are ticked, are those currently loaded to your session.

- History: this is a log of all the commands you have given the interpreter to execute. This is useful to keep a log, but also to recover something we might have forgotten to write in our script. It is searchable and has the option to send to either the console or the source file.

## Settings

As we mentioned above there are a few things you can do to customize your R Studio, but first let us change the settings of what it remembers from session to session to avoid unintended issues.

On the top menu for the IDE, click on Tools > Global Options.. and in R General:
        1. uncheck the option Restore .RData into workspace, and
        2. change the option for "Save workspace into.RData..." to Never
        
      ### Insert screencapture of global options
      
In Appearance you can change the style. Once you are done, click on "Apply" and "OK"


Now you are ready to start talking R!


```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
